# FIXME: Lower by refactoring biggest offenders
Metrics/AbcSize:
  Max: 26

# FIXME: Lower by refactoring biggest offenders
Metrics/CyclomaticComplexity:
  Max: 8

# FIXME: No clue how to fix that one line…
Metrics/LineLength:
  Max: 100
  Exclude:
    - lib/rom/rails/configuration.rb

# FIXME: Lower by refactoring biggest offenders
Metrics/MethodLength:
  Max: 22

# FIXME: Lower by refactoring biggest offenders
Metrics/PerceivedComplexity:
  Max: 10

# Don’t check temp and Rails-generated files
AllCops:
  Exclude:
    - spec/dummy/Rakefile
    - spec/dummy/config/**/*
    - spec/dummy/db/schema.rb
    - spec/dummy/db/seeds.rb
    - tmp/**/*
    - vendor/**/*

# The enforced style doesn’t match Vim’s defaults
Style/AlignParameters:
  Enabled: false

# UTF-8 is perfectly fine in comments
Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - let
    - let!
    - subject
    - watch
    - before

Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: context_dependent

# Allow compact style for specs
Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*_spec.rb

# Documentation checked by Inch CI
Style/Documentation:
  Enabled: false

# This is a shim file for those who require 'rom-mongo'
Style/FileName:
  Exclude:
    - lib/rom-rails.rb

# Early returns have their vices
Style/GuardClause:
  Enabled: false

# Need to be skipped for >-> usage
Style/Lambda:
  Enabled: false

# Multiline block chains are ok
Style/MultilineBlockChain:
  Enabled: false

# Multiline operation chains are indented
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# Model::Validator uses Model::ValidationError for this
Style/RaiseArgs:
  Exclude:
    - lib/rom/model.rb

# Don’t introduce semantic fail/raise distinction
Style/SignalException:
  EnforcedStyle: only_raise

# Need to be skipped for >-> usage
Style/SpaceAroundOperators:
  Enabled: false

# Accept both single and double quotes
Style/StringLiterals:
  Enabled: false

# Allow def self.foo; @foo; end
Style/TrivialAccessors:
  Enabled: false

Style/AccessorMethodName:
  Exclude:
    - lib/rom/rails/model/params.rb

# Allow logical `or`/`and` in conditionals
Style/AndOr:
  EnforcedStyle: conditionals
