language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks
script: "RAILS_ENV=test bundle exec rake app:db:reset app:spec"
rvm:
  - 2.3.1
  - 2.4.1
  - rbx-2
  - jruby-9.1.0.0
  - ruby-head
env:
  - RAILS_VERSION=5.1.0
  - RAILS_VERSION=5.0.0
  - RAILS_VERSION=4.2.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  exclude:
    - rvm: rbx-2
      env: RAILS_VERSION=5.0.0
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
