language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks
script: "RAILS_ENV=test bundle exec rake app:db:reset app:spec"
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-9.2.7.0
env:
  - RAILS_VERSION=6.0
  - RAILS_VERSION=5.2
  - RAILS_VERSION=5.1
  - RAILS_VERSION=5.0
  - RAILS_VERSION=4.2
notifications:
  webhooks:
    urls:
      - https://rom-rb.zulipchat.com/api/v1/external/travis?api_key=S1S2GRkXHlzlaCGyUwm7o4lg50IZrwCH&stream=notifications&topic=ci
    on_success: change
    on_failure: always
    on_start: false
matrix:
  exclude:
    - rvm: 2.4.6
      env: RAILS_VERSION=6.0
