language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks
env:
  - CODECLIMATE_REPO_TOKEN=87c9080bda25bce8e63a294f99312345c144c0f6d5eedf400fd753356fbf7dcf
script: "RAILS_ENV=test bundle exec rake app:db:reset app:spec"
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - rbx-2
  - jruby-9000
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
