language: ruby
bundler_args: --without yard guard benchmarks
script: "RAILS_ENV=test rake app:spec"
rvm:
  - 2.0
  - 2.1
  - rbx-2
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
